### ISSUE TITLE
Mail handler crashes when idling too long

### ISSUE THREAD

**Issue by phihag** [hhucn/netsec-uebungssystem#16]
When the mail handler is running, it eventually crashes (on the production mail server) with

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/phihag/teaching/netsec/netsec-uebungssystem/netsecus/__main__.py", line 18, in <module>
    _main()
  File "/home/phihag/teaching/netsec/netsec-uebungssystem/netsecus/__main__.py", line 16, in _main
    sys.exit(main())
  File "netsecus/__init__.py", line 57, in main
    mail_handler.mainloop(config)
  File "netsecus/mail_handler.py", line 52, in mainloop
    ruleLoop(config, imapmail)
  File "netsecus/mail_handler.py", line 61, in ruleLoop
    processRule(config, imapmail, rule)
  File "netsecus/mail_handler.py", line 71, in processRule
    mails = getattr(rules, step[0])(config, imapmail, mails, *step[1:])
  File "netsecus/rules.py", line 27, in filter
    imapmail.select(mailbox)
  File "/usr/lib/python2.7/imaplib.py", line 661, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib/python2.7/imaplib.py", line 1087, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 911, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.abort: command: SELECT => idle for too long
```

It should simply reconnect after a timeout. Also, we may want to rethink the rules part - it feels really strange for the mail handler to spend lots of time in a rule.

**Comment by phihag** [comment]
Oh, we are in the non-IDLE path here, so something else must be wrong.
