### ISSUE TITLE
Korrekturserver/Tornado Exception

### ISSUE THREAD

**Issue by maride** [hhucn/netsec-uebungssystem#17]
This exception gets thrown upon every HTTP connection on Python 2 (Version 2.7.9). It doesn't affect the execution as HTTP requests are processed normally. Python 3 is not affected, as of 3.4.3.

```
2015-05-04 20:41:56,321 Web server started on port 8080.
2015-05-04 20:42:19,149 401 GET / (::1) 1.20ms
2015-05-04 20:42:19,149 Uncaught exception
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/http1connection.py", line 236, in _read_message
    delegate.finish()
  File "/Library/Python/2.7/site-packages/tornado/httpserver.py", line 269, in finish
    self.delegate.finish()
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1898, in finish
    self.execute()
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1930, in execute
    f.add_done_callback(lambda f: f.exception())
AttributeError: 'NoneType' object has no attribute 'add_done_callback'
```

**Comment by maride** [comment]
Seems to be an issue with an old version of Tornado or Python.
The affected setup was Python 2.7.9 and Tornado 4.1.
On Python 2.7.10 and Tornado 4.2, the server runs without this exception.
